sh_test(
    name='combine',
    visibility=['PUBLIC'],
    test='combine.sh',
    args=[
        '-r', 'lib',
        '-r', 'lib/common',
        '-r', 'lib/decompress',
        '-o', 'contrib/declib/zstddeclib.c',
        'contrib/declib/zstddeclib-in.c']
)
