blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://muhammad-fiaz.github.io/tint.zig/
    about: Read the Tint.zig documentation, guides, API reference, and examples.
  - name: GitHub Discussions
    url: https://github.com/muhammad-fiaz/tint.zig/discussions
    about: Please ask and answer questions here.