const std = @import("std");

pub const ErrorCode = enum(c_int) {
    no_error = 0,
    generic = 1,
    prefix_unknown = 10,
    version_unsupported = 12,
    frame_parameter_unsupported = 14,
    frame_parameter_window_too_large = 16,
    corruption_detected = 20,
    checksum_wrong = 22,
    literals_header_wrong = 24,
    dictionary_corrupted = 30,
    dictionary_wrong = 32,
    dictionary_creation_failed = 34,
    parameter_unsupported = 40,
    parameter_combination_unsupported = 41,
    parameter_out_of_bound = 42,
    table_log_too_large = 44,
    max_symbol_value_too_large = 46,
    max_symbol_value_too_small = 48,
    cannot_produce_uncompressed_block = 49,
    stability_condition_not_respected = 50,
    stage_wrong = 60,
    init_missing = 62,
    memory_allocation = 64,
    workspace_too_small = 66,
    dst_size_too_small = 70,
    src_size_wrong = 72,
    dst_buffer_null = 74,
    no_forward_progress_dest_full = 80,
    no_forward_progress_input_empty = 82,
    frame_index_too_large = 100,
    seekable_io = 102,
    dst_buffer_wrong = 104,
    src_buffer_wrong = 105,
    sequence_producer_failed = 106,
    external_sequences_invalid = 107,
    max_code = 120,
};

pub const ZstdError = error{
    OutOfMemory,
    Generic,
    PrefixUnknown,
    VersionUnsupported,
    FrameParameterUnsupported,
    FrameParameterWindowTooLarge,
    CorruptionDetected,
    ChecksumWrong,
    LiteralsHeaderWrong,
    DictionaryCorrupted,
    DictionaryWrong,
    DictionaryCreationFailed,
    ParameterUnsupported,
    ParameterCombinationUnsupported,
    ParameterOutOfBound,
    TableLogTooLarge,
    MaxSymbolValueTooLarge,
    MaxSymbolValueTooSmall,
    CannotProduceUncompressedBlock,
    StabilityConditionNotRespected,
    StageWrong,
    InitMissing,
    MemoryAllocation,
    WorkspaceTooSmall,
    DstSizeTooSmall,
    SrcSizeWrong,
    DstBufferNull,
    NoForwardProgressDestFull,
    NoForwardProgressInputEmpty,
    FrameIndexTooLarge,
    SeekableIO,
    DstBufferWrong,
    SrcBufferWrong,
    SequenceProducerFailed,
    ExternalSequencesInvalid,
    BadMagic,
    BlockOversize,
    MalformedFrame,
    MalformedBlock,
    MalformedCompressedBlock,
    MalformedLiteralsSection,
    MalformedLiteralsHeader,
    MalformedSequence,
    MalformedFseTable,
    MalformedFseBits,
    MalformedHuffmanTree,
    MalformedAccuracyLog,
    MissingStartBit,
    TreelessLiteralsFirst,
    RepeatModeFirst,
    InvalidBitStream,
    UnexpectedEndOfLiteralStream,
    ReadFailed,
    EndOfStream,
    OutputBufferUndersize,
    InputBufferUndersize,
    HuffmanTreeIncomplete,
    SequenceBufferUndersize,
    ReservedBitSet,
    ReservedBlock,
    WindowSizeUnknown,
    WindowOversize,
    ContentOversize,
    DictionaryIdFlagUnsupported,
};

pub fn isError(result: usize) bool {
    return (result >> (@sizeOf(usize) * 8 - 1)) != 0;
}

pub fn getErrorCode(result: usize) ErrorCode {
    if (!isError(result)) return .no_error;
    const val: c_int = @intCast(@as(isize, @bitCast(result)));
    const code: ErrorCode = @fromBackingInt(@intCast(val));
    return if (@backingInt(code) > @backingInt(ErrorCode.max_code)) .generic else code;
}

pub fn errorCodeToError(code: ErrorCode) ZstdError {
    return switch (code) {
        .no_error => unreachable,
        .generic => error.Generic,
        .prefix_unknown => error.PrefixUnknown,
        .version_unsupported => error.VersionUnsupported,
        .frame_parameter_unsupported => error.FrameParameterUnsupported,
        .frame_parameter_window_too_large => error.FrameParameterWindowTooLarge,
        .corruption_detected => error.CorruptionDetected,
        .checksum_wrong => error.ChecksumWrong,
        .literals_header_wrong => error.LiteralsHeaderWrong,
        .dictionary_corrupted => error.DictionaryCorrupted,
        .dictionary_wrong => error.DictionaryWrong,
        .dictionary_creation_failed => error.DictionaryCreationFailed,
        .parameter_unsupported => error.ParameterUnsupported,
        .parameter_combination_unsupported => error.ParameterCombinationUnsupported,
        .parameter_out_of_bound => error.ParameterOutOfBound,
        .table_log_too_large => error.TableLogTooLarge,
        .max_symbol_value_too_large => error.MaxSymbolValueTooLarge,
        .max_symbol_value_too_small => error.MaxSymbolValueTooSmall,
        .cannot_produce_uncompressed_block => error.CannotProduceUncompressedBlock,
        .stability_condition_not_respected => error.StabilityConditionNotRespected,
        .stage_wrong => error.StageWrong,
        .init_missing => error.InitMissing,
        .memory_allocation => error.MemoryAllocation,
        .workspace_too_small => error.WorkspaceTooSmall,
        .dst_size_too_small => error.DstSizeTooSmall,
        .src_size_wrong => error.SrcSizeWrong,
        .dst_buffer_null => error.DstBufferNull,
        .no_forward_progress_dest_full => error.NoForwardProgressDestFull,
        .no_forward_progress_input_empty => error.NoForwardProgressInputEmpty,
        .frame_index_too_large => error.FrameIndexTooLarge,
        .seekable_io => error.SeekableIO,
        .dst_buffer_wrong => error.DstBufferWrong,
        .src_buffer_wrong => error.SrcBufferWrong,
        .sequence_producer_failed => error.SequenceProducerFailed,
        .external_sequences_invalid => error.ExternalSequencesInvalid,
        .max_code => unreachable,
    };
}

pub fn errorName(code: ErrorCode) []const u8 {
    return switch (code) {
        .no_error => "No error",
        .generic => "Error (generic)",
        .prefix_unknown => "Unknown frame descriptor",
        .version_unsupported => "Version not supported",
        .frame_parameter_unsupported => "Unsupported frame parameter",
        .frame_parameter_window_too_large => "Window log parameter too large",
        .corruption_detected => "Corruption detected",
        .checksum_wrong => "Checksum mismatch",
        .literals_header_wrong => "Literal header wrong",
        .dictionary_corrupted => "Dictionary corruption detected",
        .dictionary_wrong => "Dictionary mismatch",
        .dictionary_creation_failed => "Dictionary creation failed",
        .parameter_unsupported => "Unsupported parameter",
        .parameter_combination_unsupported => "Unsupported parameter combination",
        .parameter_out_of_bound => "Parameter out of bound",
        .table_log_too_large => "Table log too large",
        .max_symbol_value_too_large => "Max symbol value too large",
        .max_symbol_value_too_small => "Max symbol value too small",
        .cannot_produce_uncompressed_block => "Cannot produce uncompressed block",
        .stability_condition_not_respected => "Stability condition not respected",
        .stage_wrong => "Stage wrong",
        .init_missing => "Init missing",
        .memory_allocation => "Memory allocation failed",
        .workspace_too_small => "Workspace too small",
        .dst_size_too_small => "Destination buffer too small",
        .src_size_wrong => "Source size wrong",
        .dst_buffer_null => "Destination buffer is null",
        .no_forward_progress_dest_full => "No forward progress: dest buffer full",
        .no_forward_progress_input_empty => "No forward progress: input empty",
        .frame_index_too_large => "Frame index too large",
        .seekable_io => "Seekable IO error",
        .dst_buffer_wrong => "Destination buffer wrong",
        .src_buffer_wrong => "Source buffer wrong",
        .sequence_producer_failed => "Sequence producer failed",
        .external_sequences_invalid => "External sequences invalid",
        .max_code => "Unspecified error",
    };
}

test "error conversion" {
    const err = errorCodeToError(@fromBackingInt(@intCast(1)));
    try std.testing.expectEqual(ZstdError.Generic, err);
}

test "isError detects errors" {
    const max: usize = @bitCast(@as(isize, -1));
    try std.testing.expect(isError(max));
    try std.testing.expect(!isError(0));
    try std.testing.expect(!isError(42));
}
