\"
\" unzstd.1: This is a manual page for 'unzstd' program. This file is part of
\" the zstd <https://github.com/Cyan4973/zstd/> project.
\"

\" No hyphenation
.hy 0
.nr HY 0

.TH unzstd "1" "2014-06-20" "unzstd" "User Commands"
.SH NAME
\fBunzstd\fR - Utility based on zstd

.SH SYNOPSIS
.TP 5
\fBunzstd\fR [\fBOPTIONS\fR] [-|INPUT-FILE]

.SH DESCRIPTION
.PP
\fBunzstd\fR is an utility based on \fBzstd\fR, a fast lossless compression algorithm.

\fBunzstd\fR decompress input file, it is equivalent to \fBzstd -d\fR,

Available options are the same as \fBzstd\fR ones (man zstd).


.SH BUGS
Report bugs at:- https://github.com/Cyan4973/zstd/

.SH AUTHOR
Yann Collet
